### ISSUE TITLE
Issue selecting number of AI players (CLI)

### ISSUE THREAD

**Issue by hughwin** [BelfDev/uofg-msc-team-project#36]
When the player selects that they want to play against 1 AI oppnent, the game ends instantly.

**Comment by hughwin** [comment]
The problems in the game class. In the constructor, the number of players is set to whatever the user entered (1), but the while loop breaks because  `while (numberOfPlayers > 1)`. I will push a hotfix to Rhys' code.

**Comment by BelfDev** [comment]
Actually, the problem is with ```createAIPlayers(numberOfPlayers - DEFAULT_NUMBER_OF_HUMAN_PLAYERS)```. We can simply remove the subtraction part and we'll be ok!

**Comment by hughwin** [comment]
I've just tested it. You need to +1 to the `numberOfPlayers ` too, otherwise the while loop will still break instantly if the user selects 1.

**Comment by BelfDev** [comment]
You're right! Because the ```numberOfPlayers``` come from the user's perspective. My bad, sorry!

**Comment by hughwin** [comment]
I'll close this now, as we know what the problem is and how to fix it.
