### ISSUE TITLE
Update README to provide instructions for the online mode

### ISSUE THREAD

**Issue by BelfDev** [BelfDev/uofg-msc-team-project#57]
As pointed out by @hughwin , the current README doesn't provide any direction with regards to the online game mode. It should add the information below:

> - Start with the mvn clean mvn package goodness
> - In the root folder, there us a TopTrumps.json file. Copy this to the target directory (where the .jar files are).
> - Start the jar with the command java -jar TopTrumps.jar -o
> - Open your internet browser and connect to http://localhost:7777/toptrumps

**Comment by hughwin** [comment]
Pull request #59 deals with this.
