### ISSUE TITLE
Logger printing

### ISSUE THREAD

**Issue by rjs68** [BelfDev/uofg-msc-team-project#61]
![image](https://user-images.githubusercontent.com/42035943/74103448-f1369680-4b43-11ea-80de-e063d0a50a60.png)

These logger statements are printing at the start of the CLI game which I don't think we need and they confuse the game selection

**Comment by hughwin** [comment]
Dealt with in #55. It was for more debugging purposes.

**Comment by hughwin** [comment]
If you want to change it locally or test, change the code in the Logger class below

![image](https://user-images.githubusercontent.com/20328038/74103799-1547a700-4b47-11ea-8d8a-3131fcb1827d.png)
